model:
  name: SVM
  random_state: 12

  training:
    test_size: 0.3
    stratify: true

  scaler:
    type: standard

  hyperparameters:
    kernel: linear
    class_weight: null
    C: 87.48635893714844